# Generated by Django 2.1.3 on 2018-11-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('caminho', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'db_table': 'images',
                'ordering': ('id',),
            },
        ),
    ]
