# Generated by Django 2.1.3 on 2018-12-16 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Site', '0003_categoria_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotas', models.PositiveIntegerField(default=0)),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operacoes_do_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='user',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Site.Produto'),
        ),
    ]
