# Generated by Django 2.1.3 on 2018-12-17 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_auto_20181216_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
